package com.example.lclepro.Bean;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class LcleFreeclassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public LcleFreeclassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Integer value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Integer value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Integer value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Integer value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Integer> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Integer> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andC11IsNull() {
            addCriterion("C11 is null");
            return (Criteria) this;
        }

        public Criteria andC11IsNotNull() {
            addCriterion("C11 is not null");
            return (Criteria) this;
        }

        public Criteria andC11EqualTo(Integer value) {
            addCriterion("C11 =", value, "c11");
            return (Criteria) this;
        }

        public Criteria andC11NotEqualTo(Integer value) {
            addCriterion("C11 <>", value, "c11");
            return (Criteria) this;
        }

        public Criteria andC11GreaterThan(Integer value) {
            addCriterion("C11 >", value, "c11");
            return (Criteria) this;
        }

        public Criteria andC11GreaterThanOrEqualTo(Integer value) {
            addCriterion("C11 >=", value, "c11");
            return (Criteria) this;
        }

        public Criteria andC11LessThan(Integer value) {
            addCriterion("C11 <", value, "c11");
            return (Criteria) this;
        }

        public Criteria andC11LessThanOrEqualTo(Integer value) {
            addCriterion("C11 <=", value, "c11");
            return (Criteria) this;
        }

        public Criteria andC11In(List<Integer> values) {
            addCriterion("C11 in", values, "c11");
            return (Criteria) this;
        }

        public Criteria andC11NotIn(List<Integer> values) {
            addCriterion("C11 not in", values, "c11");
            return (Criteria) this;
        }

        public Criteria andC11Between(Integer value1, Integer value2) {
            addCriterion("C11 between", value1, value2, "c11");
            return (Criteria) this;
        }

        public Criteria andC11NotBetween(Integer value1, Integer value2) {
            addCriterion("C11 not between", value1, value2, "c11");
            return (Criteria) this;
        }

        public Criteria andC12IsNull() {
            addCriterion("C12 is null");
            return (Criteria) this;
        }

        public Criteria andC12IsNotNull() {
            addCriterion("C12 is not null");
            return (Criteria) this;
        }

        public Criteria andC12EqualTo(Integer value) {
            addCriterion("C12 =", value, "c12");
            return (Criteria) this;
        }

        public Criteria andC12NotEqualTo(Integer value) {
            addCriterion("C12 <>", value, "c12");
            return (Criteria) this;
        }

        public Criteria andC12GreaterThan(Integer value) {
            addCriterion("C12 >", value, "c12");
            return (Criteria) this;
        }

        public Criteria andC12GreaterThanOrEqualTo(Integer value) {
            addCriterion("C12 >=", value, "c12");
            return (Criteria) this;
        }

        public Criteria andC12LessThan(Integer value) {
            addCriterion("C12 <", value, "c12");
            return (Criteria) this;
        }

        public Criteria andC12LessThanOrEqualTo(Integer value) {
            addCriterion("C12 <=", value, "c12");
            return (Criteria) this;
        }

        public Criteria andC12In(List<Integer> values) {
            addCriterion("C12 in", values, "c12");
            return (Criteria) this;
        }

        public Criteria andC12NotIn(List<Integer> values) {
            addCriterion("C12 not in", values, "c12");
            return (Criteria) this;
        }

        public Criteria andC12Between(Integer value1, Integer value2) {
            addCriterion("C12 between", value1, value2, "c12");
            return (Criteria) this;
        }

        public Criteria andC12NotBetween(Integer value1, Integer value2) {
            addCriterion("C12 not between", value1, value2, "c12");
            return (Criteria) this;
        }

        public Criteria andC13IsNull() {
            addCriterion("C13 is null");
            return (Criteria) this;
        }

        public Criteria andC13IsNotNull() {
            addCriterion("C13 is not null");
            return (Criteria) this;
        }

        public Criteria andC13EqualTo(Integer value) {
            addCriterion("C13 =", value, "c13");
            return (Criteria) this;
        }

        public Criteria andC13NotEqualTo(Integer value) {
            addCriterion("C13 <>", value, "c13");
            return (Criteria) this;
        }

        public Criteria andC13GreaterThan(Integer value) {
            addCriterion("C13 >", value, "c13");
            return (Criteria) this;
        }

        public Criteria andC13GreaterThanOrEqualTo(Integer value) {
            addCriterion("C13 >=", value, "c13");
            return (Criteria) this;
        }

        public Criteria andC13LessThan(Integer value) {
            addCriterion("C13 <", value, "c13");
            return (Criteria) this;
        }

        public Criteria andC13LessThanOrEqualTo(Integer value) {
            addCriterion("C13 <=", value, "c13");
            return (Criteria) this;
        }

        public Criteria andC13In(List<Integer> values) {
            addCriterion("C13 in", values, "c13");
            return (Criteria) this;
        }

        public Criteria andC13NotIn(List<Integer> values) {
            addCriterion("C13 not in", values, "c13");
            return (Criteria) this;
        }

        public Criteria andC13Between(Integer value1, Integer value2) {
            addCriterion("C13 between", value1, value2, "c13");
            return (Criteria) this;
        }

        public Criteria andC13NotBetween(Integer value1, Integer value2) {
            addCriterion("C13 not between", value1, value2, "c13");
            return (Criteria) this;
        }

        public Criteria andC14IsNull() {
            addCriterion("C14 is null");
            return (Criteria) this;
        }

        public Criteria andC14IsNotNull() {
            addCriterion("C14 is not null");
            return (Criteria) this;
        }

        public Criteria andC14EqualTo(Integer value) {
            addCriterion("C14 =", value, "c14");
            return (Criteria) this;
        }

        public Criteria andC14NotEqualTo(Integer value) {
            addCriterion("C14 <>", value, "c14");
            return (Criteria) this;
        }

        public Criteria andC14GreaterThan(Integer value) {
            addCriterion("C14 >", value, "c14");
            return (Criteria) this;
        }

        public Criteria andC14GreaterThanOrEqualTo(Integer value) {
            addCriterion("C14 >=", value, "c14");
            return (Criteria) this;
        }

        public Criteria andC14LessThan(Integer value) {
            addCriterion("C14 <", value, "c14");
            return (Criteria) this;
        }

        public Criteria andC14LessThanOrEqualTo(Integer value) {
            addCriterion("C14 <=", value, "c14");
            return (Criteria) this;
        }

        public Criteria andC14In(List<Integer> values) {
            addCriterion("C14 in", values, "c14");
            return (Criteria) this;
        }

        public Criteria andC14NotIn(List<Integer> values) {
            addCriterion("C14 not in", values, "c14");
            return (Criteria) this;
        }

        public Criteria andC14Between(Integer value1, Integer value2) {
            addCriterion("C14 between", value1, value2, "c14");
            return (Criteria) this;
        }

        public Criteria andC14NotBetween(Integer value1, Integer value2) {
            addCriterion("C14 not between", value1, value2, "c14");
            return (Criteria) this;
        }

        public Criteria andC21IsNull() {
            addCriterion("C21 is null");
            return (Criteria) this;
        }

        public Criteria andC21IsNotNull() {
            addCriterion("C21 is not null");
            return (Criteria) this;
        }

        public Criteria andC21EqualTo(Integer value) {
            addCriterion("C21 =", value, "c21");
            return (Criteria) this;
        }

        public Criteria andC21NotEqualTo(Integer value) {
            addCriterion("C21 <>", value, "c21");
            return (Criteria) this;
        }

        public Criteria andC21GreaterThan(Integer value) {
            addCriterion("C21 >", value, "c21");
            return (Criteria) this;
        }

        public Criteria andC21GreaterThanOrEqualTo(Integer value) {
            addCriterion("C21 >=", value, "c21");
            return (Criteria) this;
        }

        public Criteria andC21LessThan(Integer value) {
            addCriterion("C21 <", value, "c21");
            return (Criteria) this;
        }

        public Criteria andC21LessThanOrEqualTo(Integer value) {
            addCriterion("C21 <=", value, "c21");
            return (Criteria) this;
        }

        public Criteria andC21In(List<Integer> values) {
            addCriterion("C21 in", values, "c21");
            return (Criteria) this;
        }

        public Criteria andC21NotIn(List<Integer> values) {
            addCriterion("C21 not in", values, "c21");
            return (Criteria) this;
        }

        public Criteria andC21Between(Integer value1, Integer value2) {
            addCriterion("C21 between", value1, value2, "c21");
            return (Criteria) this;
        }

        public Criteria andC21NotBetween(Integer value1, Integer value2) {
            addCriterion("C21 not between", value1, value2, "c21");
            return (Criteria) this;
        }

        public Criteria andC22IsNull() {
            addCriterion("C22 is null");
            return (Criteria) this;
        }

        public Criteria andC22IsNotNull() {
            addCriterion("C22 is not null");
            return (Criteria) this;
        }

        public Criteria andC22EqualTo(Integer value) {
            addCriterion("C22 =", value, "c22");
            return (Criteria) this;
        }

        public Criteria andC22NotEqualTo(Integer value) {
            addCriterion("C22 <>", value, "c22");
            return (Criteria) this;
        }

        public Criteria andC22GreaterThan(Integer value) {
            addCriterion("C22 >", value, "c22");
            return (Criteria) this;
        }

        public Criteria andC22GreaterThanOrEqualTo(Integer value) {
            addCriterion("C22 >=", value, "c22");
            return (Criteria) this;
        }

        public Criteria andC22LessThan(Integer value) {
            addCriterion("C22 <", value, "c22");
            return (Criteria) this;
        }

        public Criteria andC22LessThanOrEqualTo(Integer value) {
            addCriterion("C22 <=", value, "c22");
            return (Criteria) this;
        }

        public Criteria andC22In(List<Integer> values) {
            addCriterion("C22 in", values, "c22");
            return (Criteria) this;
        }

        public Criteria andC22NotIn(List<Integer> values) {
            addCriterion("C22 not in", values, "c22");
            return (Criteria) this;
        }

        public Criteria andC22Between(Integer value1, Integer value2) {
            addCriterion("C22 between", value1, value2, "c22");
            return (Criteria) this;
        }

        public Criteria andC22NotBetween(Integer value1, Integer value2) {
            addCriterion("C22 not between", value1, value2, "c22");
            return (Criteria) this;
        }

        public Criteria andC23IsNull() {
            addCriterion("C23 is null");
            return (Criteria) this;
        }

        public Criteria andC23IsNotNull() {
            addCriterion("C23 is not null");
            return (Criteria) this;
        }

        public Criteria andC23EqualTo(Integer value) {
            addCriterion("C23 =", value, "c23");
            return (Criteria) this;
        }

        public Criteria andC23NotEqualTo(Integer value) {
            addCriterion("C23 <>", value, "c23");
            return (Criteria) this;
        }

        public Criteria andC23GreaterThan(Integer value) {
            addCriterion("C23 >", value, "c23");
            return (Criteria) this;
        }

        public Criteria andC23GreaterThanOrEqualTo(Integer value) {
            addCriterion("C23 >=", value, "c23");
            return (Criteria) this;
        }

        public Criteria andC23LessThan(Integer value) {
            addCriterion("C23 <", value, "c23");
            return (Criteria) this;
        }

        public Criteria andC23LessThanOrEqualTo(Integer value) {
            addCriterion("C23 <=", value, "c23");
            return (Criteria) this;
        }

        public Criteria andC23In(List<Integer> values) {
            addCriterion("C23 in", values, "c23");
            return (Criteria) this;
        }

        public Criteria andC23NotIn(List<Integer> values) {
            addCriterion("C23 not in", values, "c23");
            return (Criteria) this;
        }

        public Criteria andC23Between(Integer value1, Integer value2) {
            addCriterion("C23 between", value1, value2, "c23");
            return (Criteria) this;
        }

        public Criteria andC23NotBetween(Integer value1, Integer value2) {
            addCriterion("C23 not between", value1, value2, "c23");
            return (Criteria) this;
        }

        public Criteria andC24IsNull() {
            addCriterion("C24 is null");
            return (Criteria) this;
        }

        public Criteria andC24IsNotNull() {
            addCriterion("C24 is not null");
            return (Criteria) this;
        }

        public Criteria andC24EqualTo(Integer value) {
            addCriterion("C24 =", value, "c24");
            return (Criteria) this;
        }

        public Criteria andC24NotEqualTo(Integer value) {
            addCriterion("C24 <>", value, "c24");
            return (Criteria) this;
        }

        public Criteria andC24GreaterThan(Integer value) {
            addCriterion("C24 >", value, "c24");
            return (Criteria) this;
        }

        public Criteria andC24GreaterThanOrEqualTo(Integer value) {
            addCriterion("C24 >=", value, "c24");
            return (Criteria) this;
        }

        public Criteria andC24LessThan(Integer value) {
            addCriterion("C24 <", value, "c24");
            return (Criteria) this;
        }

        public Criteria andC24LessThanOrEqualTo(Integer value) {
            addCriterion("C24 <=", value, "c24");
            return (Criteria) this;
        }

        public Criteria andC24In(List<Integer> values) {
            addCriterion("C24 in", values, "c24");
            return (Criteria) this;
        }

        public Criteria andC24NotIn(List<Integer> values) {
            addCriterion("C24 not in", values, "c24");
            return (Criteria) this;
        }

        public Criteria andC24Between(Integer value1, Integer value2) {
            addCriterion("C24 between", value1, value2, "c24");
            return (Criteria) this;
        }

        public Criteria andC24NotBetween(Integer value1, Integer value2) {
            addCriterion("C24 not between", value1, value2, "c24");
            return (Criteria) this;
        }

        public Criteria andC31IsNull() {
            addCriterion("C31 is null");
            return (Criteria) this;
        }

        public Criteria andC31IsNotNull() {
            addCriterion("C31 is not null");
            return (Criteria) this;
        }

        public Criteria andC31EqualTo(Integer value) {
            addCriterion("C31 =", value, "c31");
            return (Criteria) this;
        }

        public Criteria andC31NotEqualTo(Integer value) {
            addCriterion("C31 <>", value, "c31");
            return (Criteria) this;
        }

        public Criteria andC31GreaterThan(Integer value) {
            addCriterion("C31 >", value, "c31");
            return (Criteria) this;
        }

        public Criteria andC31GreaterThanOrEqualTo(Integer value) {
            addCriterion("C31 >=", value, "c31");
            return (Criteria) this;
        }

        public Criteria andC31LessThan(Integer value) {
            addCriterion("C31 <", value, "c31");
            return (Criteria) this;
        }

        public Criteria andC31LessThanOrEqualTo(Integer value) {
            addCriterion("C31 <=", value, "c31");
            return (Criteria) this;
        }

        public Criteria andC31In(List<Integer> values) {
            addCriterion("C31 in", values, "c31");
            return (Criteria) this;
        }

        public Criteria andC31NotIn(List<Integer> values) {
            addCriterion("C31 not in", values, "c31");
            return (Criteria) this;
        }

        public Criteria andC31Between(Integer value1, Integer value2) {
            addCriterion("C31 between", value1, value2, "c31");
            return (Criteria) this;
        }

        public Criteria andC31NotBetween(Integer value1, Integer value2) {
            addCriterion("C31 not between", value1, value2, "c31");
            return (Criteria) this;
        }

        public Criteria andC32IsNull() {
            addCriterion("C32 is null");
            return (Criteria) this;
        }

        public Criteria andC32IsNotNull() {
            addCriterion("C32 is not null");
            return (Criteria) this;
        }

        public Criteria andC32EqualTo(Integer value) {
            addCriterion("C32 =", value, "c32");
            return (Criteria) this;
        }

        public Criteria andC32NotEqualTo(Integer value) {
            addCriterion("C32 <>", value, "c32");
            return (Criteria) this;
        }

        public Criteria andC32GreaterThan(Integer value) {
            addCriterion("C32 >", value, "c32");
            return (Criteria) this;
        }

        public Criteria andC32GreaterThanOrEqualTo(Integer value) {
            addCriterion("C32 >=", value, "c32");
            return (Criteria) this;
        }

        public Criteria andC32LessThan(Integer value) {
            addCriterion("C32 <", value, "c32");
            return (Criteria) this;
        }

        public Criteria andC32LessThanOrEqualTo(Integer value) {
            addCriterion("C32 <=", value, "c32");
            return (Criteria) this;
        }

        public Criteria andC32In(List<Integer> values) {
            addCriterion("C32 in", values, "c32");
            return (Criteria) this;
        }

        public Criteria andC32NotIn(List<Integer> values) {
            addCriterion("C32 not in", values, "c32");
            return (Criteria) this;
        }

        public Criteria andC32Between(Integer value1, Integer value2) {
            addCriterion("C32 between", value1, value2, "c32");
            return (Criteria) this;
        }

        public Criteria andC32NotBetween(Integer value1, Integer value2) {
            addCriterion("C32 not between", value1, value2, "c32");
            return (Criteria) this;
        }

        public Criteria andC33IsNull() {
            addCriterion("C33 is null");
            return (Criteria) this;
        }

        public Criteria andC33IsNotNull() {
            addCriterion("C33 is not null");
            return (Criteria) this;
        }

        public Criteria andC33EqualTo(Integer value) {
            addCriterion("C33 =", value, "c33");
            return (Criteria) this;
        }

        public Criteria andC33NotEqualTo(Integer value) {
            addCriterion("C33 <>", value, "c33");
            return (Criteria) this;
        }

        public Criteria andC33GreaterThan(Integer value) {
            addCriterion("C33 >", value, "c33");
            return (Criteria) this;
        }

        public Criteria andC33GreaterThanOrEqualTo(Integer value) {
            addCriterion("C33 >=", value, "c33");
            return (Criteria) this;
        }

        public Criteria andC33LessThan(Integer value) {
            addCriterion("C33 <", value, "c33");
            return (Criteria) this;
        }

        public Criteria andC33LessThanOrEqualTo(Integer value) {
            addCriterion("C33 <=", value, "c33");
            return (Criteria) this;
        }

        public Criteria andC33In(List<Integer> values) {
            addCriterion("C33 in", values, "c33");
            return (Criteria) this;
        }

        public Criteria andC33NotIn(List<Integer> values) {
            addCriterion("C33 not in", values, "c33");
            return (Criteria) this;
        }

        public Criteria andC33Between(Integer value1, Integer value2) {
            addCriterion("C33 between", value1, value2, "c33");
            return (Criteria) this;
        }

        public Criteria andC33NotBetween(Integer value1, Integer value2) {
            addCriterion("C33 not between", value1, value2, "c33");
            return (Criteria) this;
        }

        public Criteria andC34IsNull() {
            addCriterion("C34 is null");
            return (Criteria) this;
        }

        public Criteria andC34IsNotNull() {
            addCriterion("C34 is not null");
            return (Criteria) this;
        }

        public Criteria andC34EqualTo(Integer value) {
            addCriterion("C34 =", value, "c34");
            return (Criteria) this;
        }

        public Criteria andC34NotEqualTo(Integer value) {
            addCriterion("C34 <>", value, "c34");
            return (Criteria) this;
        }

        public Criteria andC34GreaterThan(Integer value) {
            addCriterion("C34 >", value, "c34");
            return (Criteria) this;
        }

        public Criteria andC34GreaterThanOrEqualTo(Integer value) {
            addCriterion("C34 >=", value, "c34");
            return (Criteria) this;
        }

        public Criteria andC34LessThan(Integer value) {
            addCriterion("C34 <", value, "c34");
            return (Criteria) this;
        }

        public Criteria andC34LessThanOrEqualTo(Integer value) {
            addCriterion("C34 <=", value, "c34");
            return (Criteria) this;
        }

        public Criteria andC34In(List<Integer> values) {
            addCriterion("C34 in", values, "c34");
            return (Criteria) this;
        }

        public Criteria andC34NotIn(List<Integer> values) {
            addCriterion("C34 not in", values, "c34");
            return (Criteria) this;
        }

        public Criteria andC34Between(Integer value1, Integer value2) {
            addCriterion("C34 between", value1, value2, "c34");
            return (Criteria) this;
        }

        public Criteria andC34NotBetween(Integer value1, Integer value2) {
            addCriterion("C34 not between", value1, value2, "c34");
            return (Criteria) this;
        }

        public Criteria andC41IsNull() {
            addCriterion("C41 is null");
            return (Criteria) this;
        }

        public Criteria andC41IsNotNull() {
            addCriterion("C41 is not null");
            return (Criteria) this;
        }

        public Criteria andC41EqualTo(Integer value) {
            addCriterion("C41 =", value, "c41");
            return (Criteria) this;
        }

        public Criteria andC41NotEqualTo(Integer value) {
            addCriterion("C41 <>", value, "c41");
            return (Criteria) this;
        }

        public Criteria andC41GreaterThan(Integer value) {
            addCriterion("C41 >", value, "c41");
            return (Criteria) this;
        }

        public Criteria andC41GreaterThanOrEqualTo(Integer value) {
            addCriterion("C41 >=", value, "c41");
            return (Criteria) this;
        }

        public Criteria andC41LessThan(Integer value) {
            addCriterion("C41 <", value, "c41");
            return (Criteria) this;
        }

        public Criteria andC41LessThanOrEqualTo(Integer value) {
            addCriterion("C41 <=", value, "c41");
            return (Criteria) this;
        }

        public Criteria andC41In(List<Integer> values) {
            addCriterion("C41 in", values, "c41");
            return (Criteria) this;
        }

        public Criteria andC41NotIn(List<Integer> values) {
            addCriterion("C41 not in", values, "c41");
            return (Criteria) this;
        }

        public Criteria andC41Between(Integer value1, Integer value2) {
            addCriterion("C41 between", value1, value2, "c41");
            return (Criteria) this;
        }

        public Criteria andC41NotBetween(Integer value1, Integer value2) {
            addCriterion("C41 not between", value1, value2, "c41");
            return (Criteria) this;
        }

        public Criteria andC42IsNull() {
            addCriterion("C42 is null");
            return (Criteria) this;
        }

        public Criteria andC42IsNotNull() {
            addCriterion("C42 is not null");
            return (Criteria) this;
        }

        public Criteria andC42EqualTo(Integer value) {
            addCriterion("C42 =", value, "c42");
            return (Criteria) this;
        }

        public Criteria andC42NotEqualTo(Integer value) {
            addCriterion("C42 <>", value, "c42");
            return (Criteria) this;
        }

        public Criteria andC42GreaterThan(Integer value) {
            addCriterion("C42 >", value, "c42");
            return (Criteria) this;
        }

        public Criteria andC42GreaterThanOrEqualTo(Integer value) {
            addCriterion("C42 >=", value, "c42");
            return (Criteria) this;
        }

        public Criteria andC42LessThan(Integer value) {
            addCriterion("C42 <", value, "c42");
            return (Criteria) this;
        }

        public Criteria andC42LessThanOrEqualTo(Integer value) {
            addCriterion("C42 <=", value, "c42");
            return (Criteria) this;
        }

        public Criteria andC42In(List<Integer> values) {
            addCriterion("C42 in", values, "c42");
            return (Criteria) this;
        }

        public Criteria andC42NotIn(List<Integer> values) {
            addCriterion("C42 not in", values, "c42");
            return (Criteria) this;
        }

        public Criteria andC42Between(Integer value1, Integer value2) {
            addCriterion("C42 between", value1, value2, "c42");
            return (Criteria) this;
        }

        public Criteria andC42NotBetween(Integer value1, Integer value2) {
            addCriterion("C42 not between", value1, value2, "c42");
            return (Criteria) this;
        }

        public Criteria andC43IsNull() {
            addCriterion("C43 is null");
            return (Criteria) this;
        }

        public Criteria andC43IsNotNull() {
            addCriterion("C43 is not null");
            return (Criteria) this;
        }

        public Criteria andC43EqualTo(Integer value) {
            addCriterion("C43 =", value, "c43");
            return (Criteria) this;
        }

        public Criteria andC43NotEqualTo(Integer value) {
            addCriterion("C43 <>", value, "c43");
            return (Criteria) this;
        }

        public Criteria andC43GreaterThan(Integer value) {
            addCriterion("C43 >", value, "c43");
            return (Criteria) this;
        }

        public Criteria andC43GreaterThanOrEqualTo(Integer value) {
            addCriterion("C43 >=", value, "c43");
            return (Criteria) this;
        }

        public Criteria andC43LessThan(Integer value) {
            addCriterion("C43 <", value, "c43");
            return (Criteria) this;
        }

        public Criteria andC43LessThanOrEqualTo(Integer value) {
            addCriterion("C43 <=", value, "c43");
            return (Criteria) this;
        }

        public Criteria andC43In(List<Integer> values) {
            addCriterion("C43 in", values, "c43");
            return (Criteria) this;
        }

        public Criteria andC43NotIn(List<Integer> values) {
            addCriterion("C43 not in", values, "c43");
            return (Criteria) this;
        }

        public Criteria andC43Between(Integer value1, Integer value2) {
            addCriterion("C43 between", value1, value2, "c43");
            return (Criteria) this;
        }

        public Criteria andC43NotBetween(Integer value1, Integer value2) {
            addCriterion("C43 not between", value1, value2, "c43");
            return (Criteria) this;
        }

        public Criteria andC44IsNull() {
            addCriterion("C44 is null");
            return (Criteria) this;
        }

        public Criteria andC44IsNotNull() {
            addCriterion("C44 is not null");
            return (Criteria) this;
        }

        public Criteria andC44EqualTo(Integer value) {
            addCriterion("C44 =", value, "c44");
            return (Criteria) this;
        }

        public Criteria andC44NotEqualTo(Integer value) {
            addCriterion("C44 <>", value, "c44");
            return (Criteria) this;
        }

        public Criteria andC44GreaterThan(Integer value) {
            addCriterion("C44 >", value, "c44");
            return (Criteria) this;
        }

        public Criteria andC44GreaterThanOrEqualTo(Integer value) {
            addCriterion("C44 >=", value, "c44");
            return (Criteria) this;
        }

        public Criteria andC44LessThan(Integer value) {
            addCriterion("C44 <", value, "c44");
            return (Criteria) this;
        }

        public Criteria andC44LessThanOrEqualTo(Integer value) {
            addCriterion("C44 <=", value, "c44");
            return (Criteria) this;
        }

        public Criteria andC44In(List<Integer> values) {
            addCriterion("C44 in", values, "c44");
            return (Criteria) this;
        }

        public Criteria andC44NotIn(List<Integer> values) {
            addCriterion("C44 not in", values, "c44");
            return (Criteria) this;
        }

        public Criteria andC44Between(Integer value1, Integer value2) {
            addCriterion("C44 between", value1, value2, "c44");
            return (Criteria) this;
        }

        public Criteria andC44NotBetween(Integer value1, Integer value2) {
            addCriterion("C44 not between", value1, value2, "c44");
            return (Criteria) this;
        }

        public Criteria andC51IsNull() {
            addCriterion("C51 is null");
            return (Criteria) this;
        }

        public Criteria andC51IsNotNull() {
            addCriterion("C51 is not null");
            return (Criteria) this;
        }

        public Criteria andC51EqualTo(Integer value) {
            addCriterion("C51 =", value, "c51");
            return (Criteria) this;
        }

        public Criteria andC51NotEqualTo(Integer value) {
            addCriterion("C51 <>", value, "c51");
            return (Criteria) this;
        }

        public Criteria andC51GreaterThan(Integer value) {
            addCriterion("C51 >", value, "c51");
            return (Criteria) this;
        }

        public Criteria andC51GreaterThanOrEqualTo(Integer value) {
            addCriterion("C51 >=", value, "c51");
            return (Criteria) this;
        }

        public Criteria andC51LessThan(Integer value) {
            addCriterion("C51 <", value, "c51");
            return (Criteria) this;
        }

        public Criteria andC51LessThanOrEqualTo(Integer value) {
            addCriterion("C51 <=", value, "c51");
            return (Criteria) this;
        }

        public Criteria andC51In(List<Integer> values) {
            addCriterion("C51 in", values, "c51");
            return (Criteria) this;
        }

        public Criteria andC51NotIn(List<Integer> values) {
            addCriterion("C51 not in", values, "c51");
            return (Criteria) this;
        }

        public Criteria andC51Between(Integer value1, Integer value2) {
            addCriterion("C51 between", value1, value2, "c51");
            return (Criteria) this;
        }

        public Criteria andC51NotBetween(Integer value1, Integer value2) {
            addCriterion("C51 not between", value1, value2, "c51");
            return (Criteria) this;
        }

        public Criteria andC52IsNull() {
            addCriterion("C52 is null");
            return (Criteria) this;
        }

        public Criteria andC52IsNotNull() {
            addCriterion("C52 is not null");
            return (Criteria) this;
        }

        public Criteria andC52EqualTo(Integer value) {
            addCriterion("C52 =", value, "c52");
            return (Criteria) this;
        }

        public Criteria andC52NotEqualTo(Integer value) {
            addCriterion("C52 <>", value, "c52");
            return (Criteria) this;
        }

        public Criteria andC52GreaterThan(Integer value) {
            addCriterion("C52 >", value, "c52");
            return (Criteria) this;
        }

        public Criteria andC52GreaterThanOrEqualTo(Integer value) {
            addCriterion("C52 >=", value, "c52");
            return (Criteria) this;
        }

        public Criteria andC52LessThan(Integer value) {
            addCriterion("C52 <", value, "c52");
            return (Criteria) this;
        }

        public Criteria andC52LessThanOrEqualTo(Integer value) {
            addCriterion("C52 <=", value, "c52");
            return (Criteria) this;
        }

        public Criteria andC52In(List<Integer> values) {
            addCriterion("C52 in", values, "c52");
            return (Criteria) this;
        }

        public Criteria andC52NotIn(List<Integer> values) {
            addCriterion("C52 not in", values, "c52");
            return (Criteria) this;
        }

        public Criteria andC52Between(Integer value1, Integer value2) {
            addCriterion("C52 between", value1, value2, "c52");
            return (Criteria) this;
        }

        public Criteria andC52NotBetween(Integer value1, Integer value2) {
            addCriterion("C52 not between", value1, value2, "c52");
            return (Criteria) this;
        }

        public Criteria andC53IsNull() {
            addCriterion("C53 is null");
            return (Criteria) this;
        }

        public Criteria andC53IsNotNull() {
            addCriterion("C53 is not null");
            return (Criteria) this;
        }

        public Criteria andC53EqualTo(Integer value) {
            addCriterion("C53 =", value, "c53");
            return (Criteria) this;
        }

        public Criteria andC53NotEqualTo(Integer value) {
            addCriterion("C53 <>", value, "c53");
            return (Criteria) this;
        }

        public Criteria andC53GreaterThan(Integer value) {
            addCriterion("C53 >", value, "c53");
            return (Criteria) this;
        }

        public Criteria andC53GreaterThanOrEqualTo(Integer value) {
            addCriterion("C53 >=", value, "c53");
            return (Criteria) this;
        }

        public Criteria andC53LessThan(Integer value) {
            addCriterion("C53 <", value, "c53");
            return (Criteria) this;
        }

        public Criteria andC53LessThanOrEqualTo(Integer value) {
            addCriterion("C53 <=", value, "c53");
            return (Criteria) this;
        }

        public Criteria andC53In(List<Integer> values) {
            addCriterion("C53 in", values, "c53");
            return (Criteria) this;
        }

        public Criteria andC53NotIn(List<Integer> values) {
            addCriterion("C53 not in", values, "c53");
            return (Criteria) this;
        }

        public Criteria andC53Between(Integer value1, Integer value2) {
            addCriterion("C53 between", value1, value2, "c53");
            return (Criteria) this;
        }

        public Criteria andC53NotBetween(Integer value1, Integer value2) {
            addCriterion("C53 not between", value1, value2, "c53");
            return (Criteria) this;
        }

        public Criteria andC54IsNull() {
            addCriterion("C54 is null");
            return (Criteria) this;
        }

        public Criteria andC54IsNotNull() {
            addCriterion("C54 is not null");
            return (Criteria) this;
        }

        public Criteria andC54EqualTo(Integer value) {
            addCriterion("C54 =", value, "c54");
            return (Criteria) this;
        }

        public Criteria andC54NotEqualTo(Integer value) {
            addCriterion("C54 <>", value, "c54");
            return (Criteria) this;
        }

        public Criteria andC54GreaterThan(Integer value) {
            addCriterion("C54 >", value, "c54");
            return (Criteria) this;
        }

        public Criteria andC54GreaterThanOrEqualTo(Integer value) {
            addCriterion("C54 >=", value, "c54");
            return (Criteria) this;
        }

        public Criteria andC54LessThan(Integer value) {
            addCriterion("C54 <", value, "c54");
            return (Criteria) this;
        }

        public Criteria andC54LessThanOrEqualTo(Integer value) {
            addCriterion("C54 <=", value, "c54");
            return (Criteria) this;
        }

        public Criteria andC54In(List<Integer> values) {
            addCriterion("C54 in", values, "c54");
            return (Criteria) this;
        }

        public Criteria andC54NotIn(List<Integer> values) {
            addCriterion("C54 not in", values, "c54");
            return (Criteria) this;
        }

        public Criteria andC54Between(Integer value1, Integer value2) {
            addCriterion("C54 between", value1, value2, "c54");
            return (Criteria) this;
        }

        public Criteria andC54NotBetween(Integer value1, Integer value2) {
            addCriterion("C54 not between", value1, value2, "c54");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lcle_freeclass
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lcle_freeclass
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}