package com.example.lclepro.Bean;

public class LcleClassestoteachermapper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.classes
     *
     * @mbg.generated
     */
    private String classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.teacher
     *
     * @mbg.generated
     */
    private String teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.gradle
     *
     * @mbg.generated
     */
    private Integer gradle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.weekNumber
     *
     * @mbg.generated
     */
    private Integer weeknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.totleNumber
     *
     * @mbg.generated
     */
    private Integer totlenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.sum
     *
     * @mbg.generated
     */
    private Integer sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_classestoteachermapper.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.id
     *
     * @return the value of lcle_classestoteachermapper.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.id
     *
     * @param id the value for lcle_classestoteachermapper.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.classes
     *
     * @return the value of lcle_classestoteachermapper.classes
     *
     * @mbg.generated
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.classes
     *
     * @param classes the value for lcle_classestoteachermapper.classes
     *
     * @mbg.generated
     */
    public void setClasses(String classes) {
        this.classes = classes == null ? null : classes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.teacher
     *
     * @return the value of lcle_classestoteachermapper.teacher
     *
     * @mbg.generated
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.teacher
     *
     * @param teacher the value for lcle_classestoteachermapper.teacher
     *
     * @mbg.generated
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.gradle
     *
     * @return the value of lcle_classestoteachermapper.gradle
     *
     * @mbg.generated
     */
    public Integer getGradle() {
        return gradle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.gradle
     *
     * @param gradle the value for lcle_classestoteachermapper.gradle
     *
     * @mbg.generated
     */
    public void setGradle(Integer gradle) {
        this.gradle = gradle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.weekNumber
     *
     * @return the value of lcle_classestoteachermapper.weekNumber
     *
     * @mbg.generated
     */
    public Integer getWeeknumber() {
        return weeknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.weekNumber
     *
     * @param weeknumber the value for lcle_classestoteachermapper.weekNumber
     *
     * @mbg.generated
     */
    public void setWeeknumber(Integer weeknumber) {
        this.weeknumber = weeknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.totleNumber
     *
     * @return the value of lcle_classestoteachermapper.totleNumber
     *
     * @mbg.generated
     */
    public Integer getTotlenumber() {
        return totlenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.totleNumber
     *
     * @param totlenumber the value for lcle_classestoteachermapper.totleNumber
     *
     * @mbg.generated
     */
    public void setTotlenumber(Integer totlenumber) {
        this.totlenumber = totlenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.sum
     *
     * @return the value of lcle_classestoteachermapper.sum
     *
     * @mbg.generated
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.sum
     *
     * @param sum the value for lcle_classestoteachermapper.sum
     *
     * @mbg.generated
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_classestoteachermapper.deleted
     *
     * @return the value of lcle_classestoteachermapper.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_classestoteachermapper.deleted
     *
     * @param deleted the value for lcle_classestoteachermapper.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}