package com.example.lclepro.Bean;

import java.time.LocalDateTime;

public class LcleRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.gradle
     *
     * @mbg.generated
     */
    private String gradle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.classes
     *
     * @mbg.generated
     */
    private String classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.week
     *
     * @mbg.generated
     */
    private String week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.allNumber
     *
     * @mbg.generated
     */
    private String allnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.section
     *
     * @mbg.generated
     */
    private String section;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.lession
     *
     * @mbg.generated
     */
    private String lession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.teacher
     *
     * @mbg.generated
     */
    private String teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.absence
     *
     * @mbg.generated
     */
    private String absence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.person
     *
     * @mbg.generated
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_record.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.id
     *
     * @return the value of lcle_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.id
     *
     * @param id the value for lcle_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.gradle
     *
     * @return the value of lcle_record.gradle
     *
     * @mbg.generated
     */
    public String getGradle() {
        return gradle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.gradle
     *
     * @param gradle the value for lcle_record.gradle
     *
     * @mbg.generated
     */
    public void setGradle(String gradle) {
        this.gradle = gradle == null ? null : gradle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.classes
     *
     * @return the value of lcle_record.classes
     *
     * @mbg.generated
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.classes
     *
     * @param classes the value for lcle_record.classes
     *
     * @mbg.generated
     */
    public void setClasses(String classes) {
        this.classes = classes == null ? null : classes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.week
     *
     * @return the value of lcle_record.week
     *
     * @mbg.generated
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.week
     *
     * @param week the value for lcle_record.week
     *
     * @mbg.generated
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.allNumber
     *
     * @return the value of lcle_record.allNumber
     *
     * @mbg.generated
     */
    public String getAllnumber() {
        return allnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.allNumber
     *
     * @param allnumber the value for lcle_record.allNumber
     *
     * @mbg.generated
     */
    public void setAllnumber(String allnumber) {
        this.allnumber = allnumber == null ? null : allnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.section
     *
     * @return the value of lcle_record.section
     *
     * @mbg.generated
     */
    public String getSection() {
        return section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.section
     *
     * @param section the value for lcle_record.section
     *
     * @mbg.generated
     */
    public void setSection(String section) {
        this.section = section == null ? null : section.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.lession
     *
     * @return the value of lcle_record.lession
     *
     * @mbg.generated
     */
    public String getLession() {
        return lession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.lession
     *
     * @param lession the value for lcle_record.lession
     *
     * @mbg.generated
     */
    public void setLession(String lession) {
        this.lession = lession == null ? null : lession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.teacher
     *
     * @return the value of lcle_record.teacher
     *
     * @mbg.generated
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.teacher
     *
     * @param teacher the value for lcle_record.teacher
     *
     * @mbg.generated
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.absence
     *
     * @return the value of lcle_record.absence
     *
     * @mbg.generated
     */
    public String getAbsence() {
        return absence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.absence
     *
     * @param absence the value for lcle_record.absence
     *
     * @mbg.generated
     */
    public void setAbsence(String absence) {
        this.absence = absence == null ? null : absence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.person
     *
     * @return the value of lcle_record.person
     *
     * @mbg.generated
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.person
     *
     * @param person the value for lcle_record.person
     *
     * @mbg.generated
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.add_time
     *
     * @return the value of lcle_record.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.add_time
     *
     * @param addTime the value for lcle_record.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.update_time
     *
     * @return the value of lcle_record.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.update_time
     *
     * @param updateTime the value for lcle_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_record.deleted
     *
     * @return the value of lcle_record.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_record.deleted
     *
     * @param deleted the value for lcle_record.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}