package com.example.lclepro.Bean;

import java.time.LocalDateTime;

public class LcleFreeclass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C11
     *
     * @mbg.generated
     */
    private Integer c11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C12
     *
     * @mbg.generated
     */
    private Integer c12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C13
     *
     * @mbg.generated
     */
    private Integer c13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C14
     *
     * @mbg.generated
     */
    private Integer c14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C21
     *
     * @mbg.generated
     */
    private Integer c21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C22
     *
     * @mbg.generated
     */
    private Integer c22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C23
     *
     * @mbg.generated
     */
    private Integer c23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C24
     *
     * @mbg.generated
     */
    private Integer c24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C31
     *
     * @mbg.generated
     */
    private Integer c31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C32
     *
     * @mbg.generated
     */
    private Integer c32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C33
     *
     * @mbg.generated
     */
    private Integer c33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C34
     *
     * @mbg.generated
     */
    private Integer c34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C41
     *
     * @mbg.generated
     */
    private Integer c41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C42
     *
     * @mbg.generated
     */
    private Integer c42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C43
     *
     * @mbg.generated
     */
    private Integer c43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C44
     *
     * @mbg.generated
     */
    private Integer c44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C51
     *
     * @mbg.generated
     */
    private Integer c51;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C52
     *
     * @mbg.generated
     */
    private Integer c52;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C53
     *
     * @mbg.generated
     */
    private Integer c53;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.C54
     *
     * @mbg.generated
     */
    private Integer c54;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcle_freeclass.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.id
     *
     * @return the value of lcle_freeclass.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.id
     *
     * @param id the value for lcle_freeclass.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.customer_id
     *
     * @return the value of lcle_freeclass.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.customer_id
     *
     * @param customerId the value for lcle_freeclass.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C11
     *
     * @return the value of lcle_freeclass.C11
     *
     * @mbg.generated
     */
    public Integer getC11() {
        return c11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C11
     *
     * @param c11 the value for lcle_freeclass.C11
     *
     * @mbg.generated
     */
    public void setC11(Integer c11) {
        this.c11 = c11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C12
     *
     * @return the value of lcle_freeclass.C12
     *
     * @mbg.generated
     */
    public Integer getC12() {
        return c12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C12
     *
     * @param c12 the value for lcle_freeclass.C12
     *
     * @mbg.generated
     */
    public void setC12(Integer c12) {
        this.c12 = c12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C13
     *
     * @return the value of lcle_freeclass.C13
     *
     * @mbg.generated
     */
    public Integer getC13() {
        return c13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C13
     *
     * @param c13 the value for lcle_freeclass.C13
     *
     * @mbg.generated
     */
    public void setC13(Integer c13) {
        this.c13 = c13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C14
     *
     * @return the value of lcle_freeclass.C14
     *
     * @mbg.generated
     */
    public Integer getC14() {
        return c14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C14
     *
     * @param c14 the value for lcle_freeclass.C14
     *
     * @mbg.generated
     */
    public void setC14(Integer c14) {
        this.c14 = c14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C21
     *
     * @return the value of lcle_freeclass.C21
     *
     * @mbg.generated
     */
    public Integer getC21() {
        return c21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C21
     *
     * @param c21 the value for lcle_freeclass.C21
     *
     * @mbg.generated
     */
    public void setC21(Integer c21) {
        this.c21 = c21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C22
     *
     * @return the value of lcle_freeclass.C22
     *
     * @mbg.generated
     */
    public Integer getC22() {
        return c22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C22
     *
     * @param c22 the value for lcle_freeclass.C22
     *
     * @mbg.generated
     */
    public void setC22(Integer c22) {
        this.c22 = c22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C23
     *
     * @return the value of lcle_freeclass.C23
     *
     * @mbg.generated
     */
    public Integer getC23() {
        return c23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C23
     *
     * @param c23 the value for lcle_freeclass.C23
     *
     * @mbg.generated
     */
    public void setC23(Integer c23) {
        this.c23 = c23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C24
     *
     * @return the value of lcle_freeclass.C24
     *
     * @mbg.generated
     */
    public Integer getC24() {
        return c24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C24
     *
     * @param c24 the value for lcle_freeclass.C24
     *
     * @mbg.generated
     */
    public void setC24(Integer c24) {
        this.c24 = c24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C31
     *
     * @return the value of lcle_freeclass.C31
     *
     * @mbg.generated
     */
    public Integer getC31() {
        return c31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C31
     *
     * @param c31 the value for lcle_freeclass.C31
     *
     * @mbg.generated
     */
    public void setC31(Integer c31) {
        this.c31 = c31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C32
     *
     * @return the value of lcle_freeclass.C32
     *
     * @mbg.generated
     */
    public Integer getC32() {
        return c32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C32
     *
     * @param c32 the value for lcle_freeclass.C32
     *
     * @mbg.generated
     */
    public void setC32(Integer c32) {
        this.c32 = c32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C33
     *
     * @return the value of lcle_freeclass.C33
     *
     * @mbg.generated
     */
    public Integer getC33() {
        return c33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C33
     *
     * @param c33 the value for lcle_freeclass.C33
     *
     * @mbg.generated
     */
    public void setC33(Integer c33) {
        this.c33 = c33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C34
     *
     * @return the value of lcle_freeclass.C34
     *
     * @mbg.generated
     */
    public Integer getC34() {
        return c34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C34
     *
     * @param c34 the value for lcle_freeclass.C34
     *
     * @mbg.generated
     */
    public void setC34(Integer c34) {
        this.c34 = c34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C41
     *
     * @return the value of lcle_freeclass.C41
     *
     * @mbg.generated
     */
    public Integer getC41() {
        return c41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C41
     *
     * @param c41 the value for lcle_freeclass.C41
     *
     * @mbg.generated
     */
    public void setC41(Integer c41) {
        this.c41 = c41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C42
     *
     * @return the value of lcle_freeclass.C42
     *
     * @mbg.generated
     */
    public Integer getC42() {
        return c42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C42
     *
     * @param c42 the value for lcle_freeclass.C42
     *
     * @mbg.generated
     */
    public void setC42(Integer c42) {
        this.c42 = c42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C43
     *
     * @return the value of lcle_freeclass.C43
     *
     * @mbg.generated
     */
    public Integer getC43() {
        return c43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C43
     *
     * @param c43 the value for lcle_freeclass.C43
     *
     * @mbg.generated
     */
    public void setC43(Integer c43) {
        this.c43 = c43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C44
     *
     * @return the value of lcle_freeclass.C44
     *
     * @mbg.generated
     */
    public Integer getC44() {
        return c44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C44
     *
     * @param c44 the value for lcle_freeclass.C44
     *
     * @mbg.generated
     */
    public void setC44(Integer c44) {
        this.c44 = c44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C51
     *
     * @return the value of lcle_freeclass.C51
     *
     * @mbg.generated
     */
    public Integer getC51() {
        return c51;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C51
     *
     * @param c51 the value for lcle_freeclass.C51
     *
     * @mbg.generated
     */
    public void setC51(Integer c51) {
        this.c51 = c51;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C52
     *
     * @return the value of lcle_freeclass.C52
     *
     * @mbg.generated
     */
    public Integer getC52() {
        return c52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C52
     *
     * @param c52 the value for lcle_freeclass.C52
     *
     * @mbg.generated
     */
    public void setC52(Integer c52) {
        this.c52 = c52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C53
     *
     * @return the value of lcle_freeclass.C53
     *
     * @mbg.generated
     */
    public Integer getC53() {
        return c53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C53
     *
     * @param c53 the value for lcle_freeclass.C53
     *
     * @mbg.generated
     */
    public void setC53(Integer c53) {
        this.c53 = c53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.C54
     *
     * @return the value of lcle_freeclass.C54
     *
     * @mbg.generated
     */
    public Integer getC54() {
        return c54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.C54
     *
     * @param c54 the value for lcle_freeclass.C54
     *
     * @mbg.generated
     */
    public void setC54(Integer c54) {
        this.c54 = c54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.update_time
     *
     * @return the value of lcle_freeclass.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.update_time
     *
     * @param updateTime the value for lcle_freeclass.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcle_freeclass.deleted
     *
     * @return the value of lcle_freeclass.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcle_freeclass.deleted
     *
     * @param deleted the value for lcle_freeclass.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}