package com.example.lclepro.Mapper;

import com.example.lclepro.Bean.LcleRecord;
import com.example.lclepro.Bean.LcleRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface LcleRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    long countByExample(LcleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int deleteByExample(LcleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int insert(LcleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int insertSelective(LcleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    List<LcleRecord> selectByExample(LcleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    LcleRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LcleRecord record, @Param("example") LcleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LcleRecord record, @Param("example") LcleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LcleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LcleRecord record);

    @Select("SELECT DISTINCT gradle FROM lcle_classestoteachermapper")
    List<String> selectAllGradle();

    @Select("select classes from lcle_classestoteachermapper where gradle = #{gradle}")
    List<String> selectClassname(Integer gradle);
}