package com.example.lclepro.Mapper;

import com.example.lclepro.Bean.LclePermission;
import com.example.lclepro.Bean.LclePermissionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface LclePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    long countByExample(LclePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int deleteByExample(LclePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int insert(LclePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int insertSelective(LclePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    List<LclePermission> selectByExample(LclePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    LclePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LclePermission record, @Param("example") LclePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LclePermission record, @Param("example") LclePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LclePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LclePermission record);
}