package com.example.lclepro.Mapper;

import com.example.lclepro.Bean.LcleRole;
import com.example.lclepro.Bean.LcleRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LcleRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    long countByExample(LcleRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int deleteByExample(LcleRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int insert(LcleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int insertSelective(LcleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    List<LcleRole> selectByExample(LcleRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    LcleRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LcleRole record, @Param("example") LcleRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LcleRole record, @Param("example") LcleRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LcleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LcleRole record);
}