package com.example.lclepro.Mapper;

import com.example.lclepro.Bean.LcleCustomer;
import com.example.lclepro.Bean.LcleCustomerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LcleCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    long countByExample(LcleCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int deleteByExample(LcleCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int insert(LcleCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int insertSelective(LcleCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    List<LcleCustomer> selectByExample(LcleCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    LcleCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LcleCustomer record, @Param("example") LcleCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LcleCustomer record, @Param("example") LcleCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LcleCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LcleCustomer record);
}