package com.example.lclepro.Mapper;

import com.example.lclepro.Bean.LcleClassestoteachermapper;
import com.example.lclepro.Bean.LcleClassestoteachermapperExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LcleClassestoteachermapperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    long countByExample(LcleClassestoteachermapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int deleteByExample(LcleClassestoteachermapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int insert(LcleClassestoteachermapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int insertSelective(LcleClassestoteachermapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    List<LcleClassestoteachermapper> selectByExample(LcleClassestoteachermapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    LcleClassestoteachermapper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LcleClassestoteachermapper record, @Param("example") LcleClassestoteachermapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LcleClassestoteachermapper record, @Param("example") LcleClassestoteachermapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LcleClassestoteachermapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lcle_classestoteachermapper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LcleClassestoteachermapper record);
}